//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long id { get; set; }
        public long memberid { get; set; }
        public decimal trading { get; set; }
        public decimal clearing { get; set; }
        public decimal settlement { get; set; }
        public decimal collateral { get; set; }
        public System.DateTime modified { get; set; }
        public string mask { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public short state { get; set; }
    }
}
