//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public int id { get; set; }
        public Nullable<decimal> freezeValue { get; set; }
        public Nullable<decimal> totalNumber { get; set; }
        public Nullable<int> assetId { get; set; }
        public string accountId { get; set; }
        public string linkAcc { get; set; }
    }
}
