//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class API
    {
        public int id { get; set; }
        public Nullable<decimal> dopen { get; set; }
        public Nullable<decimal> dhigh { get; set; }
        public Nullable<decimal> dlow { get; set; }
        public Nullable<decimal> dclose { get; set; }
    }
}
