//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardInstrument
    {
        public int id { get; set; }
        public int boardid { get; set; }
        public int instrumentid { get; set; }
        public short state { get; set; }
        public System.DateTime modified { get; set; }
    }
}
