//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public short id { get; set; }
        public System.DateTime tdate { get; set; }
        public short type { get; set; }
        public string note { get; set; }
        public short state { get; set; }
        public System.DateTime modified { get; set; }
    }
}
