//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearingAccount
    {
        public int id { get; set; }
        public int memberid { get; set; }
        public int account { get; set; }
        public short type { get; set; }
        public int currency { get; set; }
        public decimal blnc { get; set; }
        public decimal sblnc { get; set; }
        public long linkaccount { get; set; }
        public short state { get; set; }
        public System.DateTime modified { get; set; }
    }
}
