//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColReq
    {
        public long id { get; set; }
        public Nullable<long> accId { get; set; }
        public Nullable<int> assetId { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<byte> state { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<short> reason { get; set; }
        public Nullable<int> memid { get; set; }
    }
}
