//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public int securityId { get; set; }
        public short type { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public decimal lot { get; set; }
        public decimal tick { get; set; }
        public System.DateTime sdate { get; set; }
        public System.DateTime edate { get; set; }
        public short groupId { get; set; }
        public short state { get; set; }
        public System.DateTime modified { get; set; }
        public int mmorderLimit { get; set; }
        public int orderLimit { get; set; }
        public decimal refpriceParam { get; set; }
        public long bid { get; set; }
    }
}
