//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int id { get; set; }
        public Nullable<int> securityId { get; set; }
        public Nullable<short> type { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> lot { get; set; }
        public Nullable<decimal> tick { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<short> groupId { get; set; }
        public Nullable<short> state { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> mmorderLimit { get; set; }
        public Nullable<int> orderLimit { get; set; }
        public Nullable<decimal> refpriceParam { get; set; }
    }
}
