//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public long id { get; set; }
        public Nullable<short> boardid { get; set; }
        public string dealno { get; set; }
        public Nullable<short> side { get; set; }
        public Nullable<int> memberid { get; set; }
        public Nullable<long> accountid { get; set; }
        public Nullable<int> assetid { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<short> state { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<decimal> m2m { get; set; }
        public Nullable<decimal> refPrice { get; set; }
        public Nullable<short> dealType { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<decimal> interests { get; set; }
        public Nullable<decimal> toPay { get; set; }
        public string connect { get; set; }
    }
}
