//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal2
    {
        public long id { get; set; }
        public long orderid { get; set; }
        public Nullable<long> memberid { get; set; }
        public Nullable<long> accountid { get; set; }
        public Nullable<long> member2id { get; set; }
        public Nullable<long> account2id { get; set; }
        public Nullable<decimal> assetAmount { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
    }
}
