//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public short id { get; set; }
        public Nullable<decimal> tradBuyC { get; set; }
        public Nullable<decimal> tradBuyH { get; set; }
        public Nullable<decimal> tradSellC { get; set; }
        public Nullable<decimal> tradSellH { get; set; }
        public Nullable<decimal> clearBuyC { get; set; }
        public Nullable<decimal> clearBuyH { get; set; }
        public Nullable<decimal> clearSellC { get; set; }
        public Nullable<decimal> clearSellH { get; set; }
        public Nullable<decimal> settBuyC { get; set; }
        public Nullable<decimal> settBuyH { get; set; }
        public Nullable<decimal> settSellC { get; set; }
        public Nullable<decimal> settSellH { get; set; }
        public Nullable<decimal> posBuyC { get; set; }
        public Nullable<decimal> posBuyH { get; set; }
        public Nullable<decimal> posSellC { get; set; }
        public Nullable<decimal> posSellH { get; set; }
        public Nullable<decimal> brokBuyC { get; set; }
        public Nullable<decimal> brokBuyH { get; set; }
        public Nullable<decimal> brokSellC { get; set; }
        public Nullable<decimal> brokSellH { get; set; }
        public Nullable<decimal> lossBuyC { get; set; }
        public Nullable<decimal> lossBuyH { get; set; }
        public Nullable<decimal> lossSellC { get; set; }
        public Nullable<decimal> lossSellH { get; set; }
        public Nullable<decimal> repoBuyC { get; set; }
        public Nullable<decimal> repoBuyH { get; set; }
        public Nullable<decimal> repoSellC { get; set; }
        public Nullable<decimal> repoSellH { get; set; }
        public Nullable<decimal> negoBuyC { get; set; }
        public Nullable<decimal> negoBuyH { get; set; }
        public Nullable<decimal> negoSellC { get; set; }
        public Nullable<decimal> negoSellH { get; set; }
        public Nullable<decimal> otcBuyC { get; set; }
        public Nullable<decimal> otcBuyH { get; set; }
        public Nullable<decimal> otcSellC { get; set; }
        public Nullable<decimal> otcSellH { get; set; }
        public Nullable<decimal> other { get; set; }
    }
}
