//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRight
    {
        public long ID { get; set; }
        public Nullable<long> GroupID { get; set; }
        public Nullable<int> RightID { get; set; }
        public Nullable<short> HasRight { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
