//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRight
    {
        public long ID { get; set; }
        public long GroupID { get; set; }
        public int RightID { get; set; }
        public short HasRight { get; set; }
        public System.DateTime Modified { get; set; }
    }
}
