//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public short type { get; set; }
        public string invoiceno { get; set; }
        public System.DateTime invoicedate { get; set; }
        public System.DateTime expiredate { get; set; }
        public long formid { get; set; }
        public long toid { get; set; }
        public int assetid { get; set; }
        public decimal qty { get; set; }
        public short state { get; set; }
        public System.DateTime modified { get; set; }
    }
}
