//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Margin
    {
        public int id { get; set; }
        public Nullable<decimal> buy { get; set; }
        public Nullable<decimal> sell { get; set; }
        public Nullable<short> buytype { get; set; }
        public Nullable<short> selltype { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<decimal> mbuy { get; set; }
        public Nullable<decimal> msell { get; set; }
    }
}
