//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketMaker
    {
        public int id { get; set; }
        public int contactid { get; set; }
        public int memberid { get; set; }
        public long accountid { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public int ticks { get; set; }
        public string description { get; set; }
        public int orderlimit { get; set; }
        public short state { get; set; }
        public System.DateTime modified { get; set; }
    }
}
