//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public int id { get; set; }
        public Nullable<short> type { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public Nullable<short> state { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> csid { get; set; }
        public Nullable<int> webid { get; set; }
        public Nullable<long> partid { get; set; }
    }
}
