//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demoEntities1 : DbContext
    {
        public demoEntities1()
            : base("name=demoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assets> Assets { get; set; }
        public virtual DbSet<Boards> Boards { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Participants> Participants { get; set; }
        public virtual DbSet<Session> Session { get; set; }
    }
}
