//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class netting
    {
        public long id { get; set; }
        public short dealType { get; set; }
        public long accid { get; set; }
        public long assid { get; set; }
        public System.DateTime modified { get; set; }
        public decimal total { get; set; }
        public Nullable<long> bid { get; set; }
    }
}
