//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public short state { get; set; }
        public string pcity { get; set; }
        public string pdistr { get; set; }
        public string phoroo { get; set; }
        public string pstreet { get; set; }
        public string pwebpage { get; set; }
        public string numofemp { get; set; }
        public System.DateTime modified { get; set; }
        public int csid { get; set; }
        public int webid { get; set; }
        public Nullable<short> spType { get; set; }
        public Nullable<short> coType { get; set; }
    }
}
