//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefPrice
    {
        public long contractId { get; set; }
        public Nullable<decimal> refprice1 { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string name { get; set; }
    }
}
