//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public int ID { get; set; }
        public int RightType { get; set; }
        public string KeyName { get; set; }
        public string RightCaption { get; set; }
        public string RightTooltip { get; set; }
        public short DefaultValue { get; set; }
        public int RelationID { get; set; }
        public short RightLevel { get; set; }
        public int ParentID { get; set; }
    }
}
