//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public int ID { get; set; }
        public Nullable<int> RightType { get; set; }
        public string KeyName { get; set; }
        public string RightCaption { get; set; }
        public string RightTooltip { get; set; }
        public Nullable<short> DefaultValue { get; set; }
        public Nullable<int> RelationID { get; set; }
        public Nullable<short> RightLevel { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
