//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public int id { get; set; }
        public Nullable<int> partid { get; set; }
        public Nullable<short> type { get; set; }
        public string name { get; set; }
        public Nullable<decimal> totalQty { get; set; }
        public Nullable<decimal> firstPrice { get; set; }
        public Nullable<decimal> intRate { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<short> state { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> assetId { get; set; }
    }
}
