//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public int ID { get; set; }
        public string SWName { get; set; }
        public string SWCaption { get; set; }
        public string Description { get; set; }
        public short IsClient { get; set; }
    }
}
