//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran
    {
        public long id { get; set; }
        public Nullable<long> accountId { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<short> type1 { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> currency { get; set; }
        public Nullable<int> rate { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public Nullable<short> state { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<long> memberid { get; set; }
    }
}
