//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages.dbBind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran
    {
        public long id { get; set; }
        public long accountId { get; set; }
        public short type { get; set; }
        public short type1 { get; set; }
        public decimal amount { get; set; }
        public int currency { get; set; }
        public int rate { get; set; }
        public string note { get; set; }
        public System.DateTime tdate { get; set; }
        public short state { get; set; }
        public System.DateTime modified { get; set; }
        public long userId { get; set; }
        public long memberid { get; set; }
    }
}
