//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boards
    {
        public short id { get; set; }
        public string name { get; set; }
        public Nullable<short> type { get; set; }
        public string tdays { get; set; }
        public Nullable<short> state { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string description { get; set; }
    
        public virtual Boards Boards1 { get; set; }
        public virtual Boards Boards2 { get; set; }
    }
}
